#!name=Rule补完
#!desc=Shadowrocket黑名单规则补完
[Rule]
# Ether.fi 规则
DOMAIN-SUFFIX,ether.fi,PROXY
DOMAIN-SUFFIX,etherfi.com,PROXY
DOMAIN-SUFFIX,etherfi.io,PROXY
DOMAIN-KEYWORD,etherfi,PROXY
DOMAIN-KEYWORD,ether-fi,PROXY

# Web3 / WalletConnect 钱包连接
DOMAIN-SUFFIX,walletconnect.com,PROXY
DOMAIN-SUFFIX,walletconnect.org,PROXY
DOMAIN-SUFFIX,reown.com,PROXY

DOMAIN-SUFFIX,push.apple.com,PROXY
PROCESS-NAME,apsd,PROXY
DOMAIN-SUFFIX,schwab.com,PROXY
DOMAIN-SUFFIX,schwabclient.com,PROXY
DOMAIN-SUFFIX,thinkorswim.com,PROXY
DOMAIN-SUFFIX,tdameritrade.com,PROXY
DOMAIN-SUFFIX,za.group,DIRECT
DOMAIN-SUFFIX,zabank.com,DIRECT
DOMAIN-SUFFIX,zhongan.com,DIRECT
DOMAIN-SUFFIX,claude.ai,PROXY
DOMAIN-SUFFIX,passwall2.org,PROXY,no-resolve
DOMAIN-SUFFIX,t-mobile.com,PROXY,no-resolve
DOMAIN-SUFFIX,shuzijumin.com,PROXY
DOMAIN-SUFFIX,naixi.net,PROXY
DOMAIN-SUFFIX,tokyotosho.info,PROXY
DOMAIN-SUFFIX,nadine-j.de,PROXY
DOMAIN-SUFFIX,torrentkitty.one,PROXY
DOMAIN-SUFFIX,torrentkitty.tv,PROXY
DOMAIN-SUFFIX,zoog.info,PROXY
DOMAIN-SUFFIX,aimtell.com,PROXY
DOMAIN-SUFFIX,clarity.ms,PROXY
DOMAIN-SUFFIX,aimtell.io,PROXY
DOMAIN-SUFFIX,anirena.com,PROXY
