#!name=Rule补完
#!desc=Shadowrocket黑名单规则补完
[Rule]

DOMAIN-SUFFIX,za.group,DIRECT
DOMAIN-SUFFIX,zabank.com,DIRECT
DOMAIN-SUFFIX,zhongan.com,DIRECT

DOMAIN-SUFFIX,passwall2.org,PROXY,no-resolve
DOMAIN-SUFFIX,t-mobile.com,PROXY,no-resolve
DOMAIN-SUFFIX,shuzijumin.com,PROXY
DOMAIN-SUFFIX,naixi.net,PROXY
DOMAIN-SUFFIX,tokyotosho.info,PROXY
DOMAIN-SUFFIX,nadine-j.de,PROXY
DOMAIN-SUFFIX,torrentkitty.one,PROXY
DOMAIN-SUFFIX,torrentkitty.tv,PROXY
DOMAIN-SUFFIX,zoog.info,PROXY
DOMAIN-SUFFIX,aimtell.com,PROXY
DOMAIN-SUFFIX,clarity.ms,PROXY
DOMAIN-SUFFIX,aimtell.io,PROXY
DOMAIN-SUFFIX,anirena.com,PROXY
DOMAIN-SUFFIX,push.apple.com,PROXY
